---
template_path: base.yaml
stack_name: bsmnmanifests
parameters:
  MainContainer: bsmnetwork/ndasynapse-manifests:v3.0.0
  Department: "SysBio"
  Project: "bsmn"
  OwnerEmail: "kenneth.daily@sagebase.org"
  VpcName: "computevpc"
