---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Batch jobs for BSMN ndasynapse-manifests application.

Parameters:
  VpcName:
    Description: The name of the VPC to use for this Batch environment.
    Type: String
    AllowedValues: ["computevpc", "sandcastlevpc"]
  MainContainer:
    Description: The docker container image.
    Type: String
  Department:
    Description: 'The department for this resource'
    Type: String
    AllowedPattern: '^\S*$'
    ConstraintDescription: 'Must be string with no spaces'
  Project:
    Description: 'The name of the project that this resource is used for'
    Type: String
    AllowedPattern: '^\S*$'
    ConstraintDescription: 'Must be string with no spaces'
  OwnerEmail:
    Description: 'Email address of the owner of this resource'
    Type: String
    AllowedPattern: '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
    ConstraintDescription: 'Must be an acceptable email address syntax(i.e. joe.smith@sagebase.org)'

Resources:
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: "rate(1 day)"
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt BatchJobQueue.Arn
          Id: !Sub '${AWS::StackName}-OriginalBatchJob-daily'
          BatchParameters:
            ArrayProperties:
              Size: 3
            JobDefinition: !Ref OriginalBatchJob
            JobName: !Sub '${AWS::StackName}-OriginalBatchJob-daily'
        -
          Arn: !GetAtt BatchJobQueue.Arn
          Id: !Sub '${AWS::StackName}-LiveBatchJob-daily'
          BatchParameters:
            ArrayProperties:
              Size: 3
            JobDefinition: !Ref LiveBatchJob
            JobName: !Sub '${AWS::StackName}-LiveBatchJob-daily'

  InvokeBatchJobQueuePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'batch:SubmitJob'
            Resource:
              - !GetAtt BatchJobQueue.Arn
              - !GetAtt OriginalBatchJob.Arn
              - !GetAtt LiveBatchJob.Arn
      Roles:
        - !Ref BatchInstanceRole

  MyCloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 365

  PublishToCloudwatchPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
              - 'logs:DescribeLogGroups'
            Resource: !GetAtt MyCloudWatchLogGroup.Arn
      Roles:
        - !Ref BatchInstanceRole

  BatchServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
        - !Ref PublishToCloudwatchPolicy
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/"

  BatchInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/"

  BatchInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref BatchInstanceRole

  BatchComputeEnvironment:
    Type: "AWS::Batch::ComputeEnvironment"
    Properties:
      Type: MANAGED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      State: ENABLED
      ComputeResources:
        Type: EC2
        MaxvCpus: 256
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub '${AWS::Region}-${VpcName}-VpnSecurityGroup'
        Subnets:
          - Fn::ImportValue:
              !Sub '${AWS::Region}-${VpcName}-PrivateSubnet1'
          - Fn::ImportValue:
              !Sub '${AWS::Region}-${VpcName}-PrivateSubnet2'
        MinvCpus: 0
        InstanceRole: !GetAtt BatchInstanceProfile.Arn
        InstanceTypes:
          - optimal
        DesiredvCpus: 8
        Tags:
          "Name": !Sub '${AWS::StackName}-BatchComputeEnvironment'
          "Department": !Ref Department
          "Project": !Ref Project
          "OwnerEmail": !Ref OwnerEmail

  BatchJobQueue:
    Type: "AWS::Batch::JobQueue"
    Properties:
      ComputeEnvironmentOrder:
        - ComputeEnvironment: !Ref BatchComputeEnvironment
          Order: 1
      Priority: 1
      State: ENABLED

  OriginalBatchJob:
    Type: 'AWS::Batch::JobDefinition'
    Properties:
      Type: container
      ContainerProperties:
        Image: !Ref MainContainer
          Vcpus: 2
        Memory: 8192
        Command:
          - /run-original-manifests.sh

  LiveBatchJob:
    Type: 'AWS::Batch::JobDefinition'
    Properties:
      Type: container
      ContainerProperties:
        Image: !Ref MainContainer
        Vcpus: 2
        Memory: 8192
        Command:
          - /run-live-manifests.sh

Outputs:
  MyCloudWatchLogGroup:
    Value: !Ref MyCloudWatchLogGroup
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-CloudWatchLogGroup'
  BatchComputeEnvironment:
    Value: !Ref BatchComputeEnvironment
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BatchComputeEnvironment'
  BatchJobQueue:
    Value: !Ref BatchJobQueue
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BatchJobQueue'
  OriginalBatchJob:
    Value: !Ref OriginalBatchJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-OriginalBatchJob'
  LiveBatchJob:
    Value: !Ref LiveBatchJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-LiveBatchJob'
